//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppServiceScenarios
{


    public partial class Default
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// StatusPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel StatusPanel;

        /// <summary>
        /// StatusTitle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label StatusTitle;

        /// <summary>
        /// StatusMessage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal StatusMessage;

        /// <summary>
        /// BackButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button BackButton;

        /// <summary>
        /// Button1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button Button1;

        /// <summary>
        /// Button2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button Button2;

        /// <summary>
        /// Button3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button Button3;

        /// <summary>
        /// Button4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button Button4;

        /// <summary>
        /// ButtonHttp500ParallelReal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button ButtonHttp500ParallelReal;

        /// <summary>
        /// ButtonSlow10 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button ButtonSlow10;

        /// <summary>
        /// ButtonSlow60 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button ButtonSlow60;

        /// <summary>
        /// ButtonSlow10x100 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button ButtonSlow10x100;

        /// <summary>
        /// ButtonSlow60x100 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button ButtonSlow60x100;

        /// <summary>
        /// ButtonSlow10ParallelReal control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button ButtonSlow10ParallelReal;

        /// <summary>
        /// Button400 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button Button400;

        /// <summary>
        /// Button401 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button Button401;

        /// <summary>
        /// Button403 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button Button403;

        /// <summary>
        /// Button404 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button Button404;

        /// <summary>
        /// Button429 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button Button429;

        /// <summary>
        /// Button502 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button Button502;

        /// <summary>
        /// Button503 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button Button503;

        /// <summary>
        /// Button504 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button Button504;

        /// <summary>
        /// ButtonThreadPoolStarve control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button ButtonThreadPoolStarve;

        /// <summary>
        /// ButtonDeadlock control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button ButtonDeadlock;

        /// <summary>
        /// ButtonMemoryLeak control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button ButtonMemoryLeak;

        /// <summary>
        /// ButtonLargePayload control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button ButtonLargePayload;

        /// <summary>
        /// ButtonOutboundHang control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button ButtonOutboundHang;

        /// <summary>
        /// ButtonDiskIO control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button ButtonDiskIO;

        /// <summary>
        /// ButtonFailFast control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button ButtonFailFast;

        /// <summary>
        /// Button408 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button Button408;

        /// <summary>
        /// ButtonBgCrash control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button ButtonBgCrash;

        /// <summary>
        /// ButtonSocketExhaust control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button ButtonSocketExhaust;

        /// <summary>
        /// ButtonLOH control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button ButtonLOH;

        /// <summary>
        /// ButtonThrottled control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button ButtonThrottled;

        /// <summary>
        /// ButtonMixedBurst control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button ButtonMixedBurst;

        /// <summary>ButtonDNSFail control.</summary>
        protected global::System.Web.UI.WebControls.Button ButtonDNSFail;

        /// <summary>ButtonSqlConnectionPoolExhaust control.</summary>
        protected global::System.Web.UI.WebControls.Button ButtonSqlConnectionPoolExhaust;

        /// <summary>ButtonSqlSlowQuery control.</summary>
        protected global::System.Web.UI.WebControls.Button ButtonSqlSlowQuery;

        /// <summary>ButtonRedisTimeout control.</summary>
        protected global::System.Web.UI.WebControls.Button ButtonRedisTimeout;

        /// <summary>ButtonInstanceIdentity control.</summary>
        protected global::System.Web.UI.WebControls.Button ButtonInstanceIdentity;

        /// <summary>ButtonCustomEventBurst control.</summary>
        protected global::System.Web.UI.WebControls.Button ButtonCustomEventBurst;

        /// <summary>ButtonAvailabilityTestEndpoint control.</summary>
        protected global::System.Web.UI.WebControls.Button ButtonAvailabilityTestEndpoint;

        /// <summary>ButtonHealthCheckFailing control.</summary>
        protected global::System.Web.UI.WebControls.Button ButtonHealthCheckFailing;

        /// <summary>ButtonTls10Only control.</summary>
        protected global::System.Web.UI.WebControls.Button ButtonTls10Only;

        /// <summary>ButtonMissingAppSetting control.</summary>
        protected global::System.Web.UI.WebControls.Button ButtonMissingAppSetting;

        /// <summary>LoadTestCount control.</summary>
        protected global::System.Web.UI.WebControls.TextBox LoadTestCount;

        /// <summary>LoadTestConcurrency control.</summary>
        protected global::System.Web.UI.WebControls.TextBox LoadTestConcurrency;

        /// <summary>LoadTestPath control.</summary>
        protected global::System.Web.UI.WebControls.TextBox LoadTestPath;

        /// <summary>ButtonRunLoadTest control.</summary>
        protected global::System.Web.UI.WebControls.Button ButtonRunLoadTest;
    }
}
